package com.nek.mysaasapp.model;

public interface ThymeleafConstants {

    String MANAGE_URL_THYMELEAF_MODEL_ATTRIBUTE_NAME = "manageUrl";
    String EMAIL_THYMELEAF_MODEL_ATTRIBUTE_NAME = "email";
    String PREMIUM_VALID_TO_THYMELEAF_MODEL_ATTRIBUTE_NAME = "premiumValidTo";
    String TRANSACTION_THYMELEAF_MODEL_ATTRIBUTE_NAME = "transactions";
    String INITIAL_BALANCE_THYMELEAF_MODEL_ATTRIBUTE_NAME = "initialBalance";
    String TOTAL_INCOME_THYMELEAF_MODEL_ATTRIBUTE_NAME = "totalIncome";
    String TOTAL_EXPENSE_THYMELEAF_MODEL_ATTRIBUTE_NAME = "totalExpense";
    String TOTAL_TAX_AMOUNT_THYMELEAF_MODEL_ATTRIBUTE_NAME = "totalTaxAmount";
    String CURRENT_AMOUNT_THYMELEAF_MODEL_ATTRIBUTE_NAME = "currentAmount";
    String STATS_THYMELEAF_MODEL_ATTRIBUTE_NAME = "stats";
    String FIRST_YEAR_THYMELEAF_MODEL_ATTRIBUTE_NAME = "firstYear";
    String LATEST_YEAR_THYMELEAF_MODEL_ATTRIBUTE_NAME = "latestYear";
    String SELECTED_YEAR_THYMELEAF_MODEL_ATTRIBUTE_NAME = "selectedYear";
}
